name = "Conan"
type = "package-manager"

[resolve]
git-url = "https://github.com/conan-io/conan"

[platform.linux]
download-file = "conan-{version}-linux-{arch}.tgz"
exe-path = "conan"
archive-prefix = ""

[platform.macos]
download-file = "conan-{version}-macos-{arch}.tgz"
exe-path = "conan"
archive-prefix = ""

[platform.windows]
download-file = "conan-{version}-windows-{arch}.zip"
exe-path = "conan.exe"
archive-prefix = ""

[install]
download-url = "https://github.com/conan-io/conan/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"

[install.exes.conan]
exe-path = "conan"
primary = true
