name = "Conan"
type = "package-manager"

[resolve]
git-url = "https://github.com/conan-io/conan"

[platform]
download-file = "conan-{version}-{os}-{arch}.tgz"
[platform.windows]
download-file = "conan-{version}-{os}-{arch}.zip"

[install]
download-url = "https://github.com/conan-io/conan/releases/download/v{version}/{download_file}"
[install.exes]
[install.exes.conan]
exe-path = "conan"
primary = true
